### ISSUE TITLE
Failes with unhandled error on Windows

### ISSUE THREAD

**Issue by inikulin** [timoxley/pkgfiles#7]
```
$ pkgfiles
Warning: Could not find fstream-npm in global npm.
You may not see matching behaviour.

c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\node_modules\pretty-by
tes\pretty-bytes.js:18
                        throw new TypeError('Expected a number');
                        ^

TypeError: Expected a number
    at prettyBytes (c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\no
de_modules\pretty-bytes\pretty-bytes.js:18:10)
    at c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\bin\pkgfiles.js
:149:62
    at Array.map (native)
    at c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\bin\pkgfiles.js
:145:4
    at once (c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\index.js:
129:5)
    at c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\index.js:157:28

    at c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\index.js:108:16

    at f (c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\node_modules
\map-limit\node_modules\once\once.js:17:25)
    at flush (c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\node_mod
ules\map-limit\index.js:27:14)
    at c:\Users\ifaaan\AppData\Roaming\npm\node_modules\pkgfiles\node_modules\ma
p-limit\index.js:51:7
```

Tried on two Windows machines with Win7/Win8.1. On MacOS it works fine though.

**Comment by popomore** [comment]
Do you have NODE_PATH env?

Ivan Nikulin
notifications@github.com>于2016年1月29日 周五上午4:45写道：

**Comment by inikulin** [comment]
@popomore Sure.

**Comment by popomore** [comment]
Add it refer to global node_models, you can google it.

**Comment by inikulin** [comment]
@popomore 
I'm not sure it's the cause of the issue, since according to the code pkgfiles performs fallback to it's locally installed `fstream-npm` if it's can't find it in the global install.

**Comment by timoxley** [comment]
hm, weird that it gives this particular error:
`TypeError: Expected a number`
since the line it refers to explicitly checks for number:

`if (typeof entry.diskSize === 'number') entry.diskSize = bytes(entry.diskSize)`

so `entry.diskSize` must be `NaN`. 

I'm guessing this is a windows compatibility issue with `du` 

https://github.com/rvagg/node-du

@inikulin I don't have a windows machine on me as I'm travelling… can you investigate?

**Comment by inikulin** [comment]
@timoxley I'll try to take a look tomorrow

**Comment by inikulin** [comment]
OK, I've made quick some investigation. For some reason `stat.blocks` in `undefined`, so `diskSize` will be converted to `NaN` here: https://github.com/timoxley/pkgfiles/blob/master/index.js#L56. Since, there is no check for the `NaN` in CLI, the following line leads to error: https://github.com/timoxley/pkgfiles/blob/master/bin/pkgfiles.js#L149
Unfortunately, I don't have time currently to dig deeper. But I hope this info will be useful.

**Comment by nolanlawson** [comment]
FWIW this tool works on Bash on Ubuntu on Windows (aka Bash on Windows).

**Comment by revelt** [comment]
This tool seems to work, but I get this very message on Mac. It shows up even installing `fstream-npm` globally:

<img width="444" alt="fstream" src="https://user-images.githubusercontent.com/8344688/34102559-8509e5f0-e3e1-11e7-9adc-860885ebda02.png">

Maybe the npm API has changed since? Why can't we consume standalone `fstream-npm`? It npm uses it themselves and we're consuming the latest release of it, there can't be mismatch in the results output, can it?

**Comment by olton** [comment]
Hi! pkgfiles ver 2.3.2, WIndows 10, Node v11.5.0, npm v6.10.0

![2019-07-12-19-56-01](https://user-images.githubusercontent.com/365108/61145038-2d871300-a4df-11e9-9ebc-75c62131fa9a.jpg)
